name: Bicep ARM-Deploy Job

on:
  push:
    branches: 
      - main
  workflow_dispatch:

env:
  subscriptionId: ${{secrets.SUBSCRIPTION_ID}}

jobs:

  armDeployStaging:
    name: Deploy to Staging 
    runs-on: ubuntu-latest

    env: 
      resource_group_name: rg-stg-devlab
      location: eastus

    environment: 
      name: staging

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with: 
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Deploy RG ${{env.resource_group_name}}
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{env.subscriptionId}}
          region: ${{env.location}}
          template: ./bicep-templates/resourcegroup.bicep
          parameters:
            resourceGroupName=${{env.resource_group_name}} 
            location=${{env.location}}
          deploynmentName: ${{env.resource_group_name}}

      - name: Deploy vNet
        uses: Azure/arm-deploy@v1
        with: 
          scope: resourcegroup
          resource_group_name: ${{env.resource_group_name}}
          subscriptionId: ${{env.subscriptionId}}
          template: ./bicep-templates/vNet.bicep
          parameters: 
            vNetPrefix=stg
            location=${{env.location}}


  armDeployProduction:
    name: Deploy to Production
    runs-on: ubuntu-latest

    env: 
      resource_group_name: rg-prod-devlab
      location: westus2
    environment: 
      name: production

    needs: armDeployStaging
    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with: 
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Deploy RG ${{env.resource_group_name}}
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{env.subscriptionId}}
          region: ${{env.location}}
          template: ./bicep-templates/resourcegroup.bicep
          parameters:
            resourceGroupName=${{env.resource_group_name}} 
            location=${{env.location}}
          deploynmentName: ${{env.resource_group_name}}

      - name: Deploy vNet
        uses: Azure/arm-deploy@v1
        with: 
          scope: resourcegroup
          resource_group_name: ${{env.resource_group_name}}
          subscriptionId: ${{env.subscriptionId}}
          template: ./bicep-templates/vNet.bicep
          parameters: 
            vNetPrefix=prod
            location=${{env.location}}